spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/employeemanager
    password: 'Erdemerdem.01'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update